// Universal Wallet & Redirect Payment Adapter.
//
// Architectural Note:
// Across TapPay's ecosystem, numerous regional e-wallets, BNPL solutions, and
// alternative payment rails (JKO Pay, LINE Pay, Pi Wallet, Easy Wallet, iPASS MONEY,
// PXPay Plus, Plus Pay, GoGo Pay, OPPay, Pay Later, AFTEE, ATM Virtual Account, and
// Cash on Delivery) share an identical architectural pattern on the front-end:
//   1. Request Prime: call `TPDirect.[walletNamespace].getPrime(cb)` -> returns `{ prime: '...' }`
//   2. Backend Processing: send prime to merchant server -> calls TapPay Pay-by-Prime -> returns `payment_url`.
//   3. Redirect: call `TPDirect.redirect(payment_url)` (or browser navigation) to authorize or display payment details.
//
// Rather than maintaining 13 repetitive boilerplate adapter classes, this Bounded Adapter
// uniformly abstracts all token-and-redirect payment rails, providing type safety,
// consistent error formatting, and a seamless developer interface.

import { TapPayError } from '../core/errors.js';

export const WALLET_METADATA = Object.freeze({
  jkoPay: { name: 'JKO Pay', title: '街口支付', icon: '🛒' },
  linePay: { name: 'LINE Pay', title: 'LINE Pay', icon: '💬' },
  piWallet: { name: 'Pi Wallet', title: 'Pi 拍錢包', icon: '🅿️' },
  easyWallet: { name: 'Easy Wallet', title: '悠遊付 (EASY WALLET)', icon: '🚌' },
  iPassMoney: { name: 'iPASS MONEY', title: 'iPASS MONEY (一卡通)', icon: '💳' },
  pxPayPlus: { name: 'PXPay Plus', title: '全支付 (PXPay Plus)', icon: '🌟' },
  plusPay: { name: 'Plus Pay', title: '台灣Pay (Plus Pay)', icon: '🇹🇼' },
  gogoPay: { name: 'GoGo Pay', title: 'GoGo Pay', icon: '⚡' },
  opPay: { name: 'OP Pay', title: 'OPEN 錢包 (OP Pay)', icon: '🏪' },
  payLater: { name: 'Pay Later', title: 'Atome / BNPL 後付款', icon: '⏳' },
  aftee: { name: 'AFTEE', title: 'AFTEE 先享後付', icon: '🛍️' },
  virtualAccount: { name: 'Virtual Account', title: 'ATM 虛擬帳號轉帳', icon: '🏧' },
  cashOnDelivery: { name: 'Cash On Delivery', title: '超商取貨付款', icon: '📦' },
});

export class WalletPayment {
  /**
   * @param {import('../core/client.js').TapPayClient} client
   * @param {string} walletType  Namespace in TPDirect (e.g. 'jkoPay', 'linePay')
   * @param {string} [displayName]  Friendly label for UI display
   */
  constructor(client, walletType, displayName) {
    this._client = client;
    this.walletType = walletType;
    this.displayName = displayName || WALLET_METADATA[walletType]?.title || walletType;
  }

  /**
   * Request a Prime token for this wallet / payment method.
   * @returns {Promise<{prime:string, method:string, result:object}>}
   */
  async getPrime() {
    const TPDirect = await this._client.ready();
    const namespace = TPDirect[this.walletType];

    if (!namespace || typeof namespace.getPrime !== 'function') {
      throw new TapPayError(`Payment method '${this.walletType}' is not available in TPDirect SDK`, {
        code: TapPayError.CODES.WALLET_UNAVAILABLE,
      });
    }

    return new Promise((resolve, reject) => {
      const callback = (errOrResult, maybeResult) => {
        // TapPay SDK sometimes passes (err, result) and sometimes just (result) depending on wallet SDK version
        let result = maybeResult || errOrResult;
        if (errOrResult && maybeResult && errOrResult.status && errOrResult.status !== 0) {
          result = errOrResult;
        }

        const status = result?.status ?? (errOrResult instanceof Error ? 1 : 0);
        const prime = result?.prime || result?.card?.prime || (typeof result === 'string' ? result : null);

        if (status !== 0 && status !== '0' || !prime) {
          return reject(
            new TapPayError(result?.msg || `Failed to get prime for ${this.displayName}`, {
              status: status,
              code: TapPayError.CODES.GET_PRIME_FAILED,
              cause: result || errOrResult,
            })
          );
        }

        resolve({
          method: this.walletType,
          prime: prime,
          result: result,
        });
      };

      try {
        // Try calling getPrime with callback
        namespace.getPrime(callback);
      } catch (e) {
        reject(new TapPayError(`Exception during ${this.walletType}.getPrime: ${e.message}`, {
          code: TapPayError.CODES.GET_PRIME_FAILED,
          cause: e,
        }));
      }
    });
  }

  /**
   * Redirect user browser to the payment URL returned by merchant backend Pay-by-Prime API.
   * @param {string} paymentUrl  The checkout/auth link generated by TapPay backend server.
   */
  async redirect(paymentUrl) {
    if (!paymentUrl) {
      throw new TapPayError('redirect() requires a valid paymentUrl', {
        code: TapPayError.CODES.REDIRECT_FAILED,
      });
    }
    const TPDirect = await this._client.ready();
    if (TPDirect.redirect && typeof TPDirect.redirect === 'function') {
      TPDirect.redirect(paymentUrl);
    } else {
      window.location.href = paymentUrl;
    }
  }
}
